#!/bin/bash
#
#

DIR=`dirname $(readlink -f $0)`
. league.dat
rsvpLogFile="${DIR}/mail/rsvp.log"

IFS='~' read -r GAME_ID GAME_TIMESTAMP GAME_DAY GAME_START GAME_LOCATION GAME_END GAME_ACTIVE < <(grep "$1" ${SCHEDULE})

. ${DIR}/admin/functions $DIR
. ${DIR}/data/league.cfg

echo "GAME_ID $GAME_ID IN_FILE: $IN_FILE"
# Send the email to the ORGANIZER telling them that at least one
# regular goaolie has not yet responded
goalieCount=`getConfirmedGoalieCount`
echo "$goalieCount"
if [ "${emailStatus}" == "enabled" ] &&
   [ "${goalieNoResponseNotify}" == "true" ] && [ $goalieCount -ne ${maxGoalies} ] ; then
    adminSendNoResponseGoalieEmail
  logInfo "Goalie Count: $goalieCount Sent: adminSendNoResponseGoalieEmail" >> $rsvpLogFile
  else
  logInfo "Goalie count: $goalieCount" >> $rsvpLogFile
fi
    